CREATE TABLE pet(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(25) NOT NULL,
    idade DECIMAL(4,2) NOT NULL,
    sexo_pet VARCHAR(6) NOT NULL,
    tipo_pet VARCHAR(4) NOT NULL,
    peso DECIMAL(4,2) NOT NULL,
    raca VARCHAR(35) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
